# Generated by Django 5.0.7 on 2024-07-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
