# Generated by Django 5.0.7 on 2024-07-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_city_country_industry_state_yearfounded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.CharField(blank=True, null=True),
        ),
    ]
