# Generated by Django 5.0.7 on 2024-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_alter_company_current_employee_estimate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='locality',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
